### ISSUE TITLE
Could you please update the glob-parent to the 5.2.0, your current version is having a security vulnerability

### ISSUE THREAD

**Issue by ChakramCPP** [nicolo-ribaudo/chokidar-2#2]
https://github.com/nicolo-ribaudo/chokidar-2/blob/a54d3bac3760faa8432a741809b2b0a0469f5fdb/package.json#L14

**Comment by nicolo-ribaudo** [comment]
`glob-parent@5.2.0` does not exist: https://www.npmjs.com/package/glob-parent

Anyway, this package is meant to be a 1:1 copy of `chokidar@2` but without the `fsevents` dependency. Since `chokidar@2` won't have any new release, this package is "frozen".

As far as I know, this package is only used by `@babel/cli` and only when using Node.js 6: if you are worried about `glob-parent`'s vulnerability, just update to Node.js 10+ (Node.js 6 is not maintained anymore, so it shouldn't be used regardless).
